### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Prachiti9**
Updated README with section about filing issue in this repo.

### CODE REVIEW

**Review by mrfaizal — APPROVED** [review]

**Review by wenlock — APPROVED** [review]
✅

**Review by lingrino — APPROVED** [review]
Reminder this is a public repo 😄

**Comment by wenlock** [comment]
> Reminder this is a public repo

Oh wow, didn't realize that, thank you for pointing it out! 

I think we'd want to leave on issues for this repo in that case.

**Review by wenlock — CHANGES_REQUESTED** [review]
How do y'all think we should handle public repos?

**Comment by Prachiti9** [comment]
thanks for pointing that out @mrfaizal.

**Comment by Prachiti9** [comment]
I think we should leave issues in same repo if its public.

**Comment by lingrino** [comment]
FYI I lost access to this repo when I left GitHub but I'm the original author and happy to keep maintaining it and responding to issues if someone can add be back as a maintainer.

**Comment by wenlock** [comment]
> FYI I lost access to this repo when I left GitHub but I'm the original author and happy to keep maintaining it and responding to issues if someone can add me back as a maintainer.

Thats funny we don't have access either. Wondering if you wouldn't mind sharing the story on why we OSS'd the work?

**Comment by lingrino** [comment]
Everyone on the SRE/Service Catalog team should have admin access. cc @ninjapenguin This started originally as a chaos engineering project. It was open sourced just because it's generic and was fun to share with more people.

**Comment by wenlock** [comment]
OK, thats great @lingrino. We'll do a little leg work and see if we can't get back to you on doing some co-maintership here as well.

Thanks!

**Comment by Prachiti9** [comment]
With reference to conversation above, we dont want to commit this change. For public repos, we will keep the issues in same repo. Closing this PR out.

**Comment by wenlock** [comment]
@lingrino so that you can continue to provide maintainership on the repo I've added you as admin. We are taking a backlog issue to make sure the repo is still relevant for internal services as well so will get back to you on more about that as well to see what we might do with future maintainership. For now, thanks so much for helping us maintain it. We've added our team as GitHub maintainers as well for any other updates/fixes we might have to work through.

Thanks! 💟

**Comment by lingrino** [comment]
Thank you!

**Pull request closed without merging**
